version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lesson_1
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5434:5432

  client:
    build:
      context: ./website/client
    container_name: lesson-001-client
    environment:
      REACT_APP_WEBSITE_NAME: Social
      REACT_APP_BACKEND_HOST: localhost # Since requests come from browser not docker, since SSR not currently used
      REACT_APP_BACKEND_PORT: 8080
    ports:
      - 3000:3000

  server:
    build:
      context: ./website/server
    depends_on:
      - db
    environment:
      PORT: 8080
      POSTGRES_DB: lesson_1
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    links:
      - db
    ports:
      - "8080:8080"
    container_name: lesson-001-server